### ISSUE TITLE
Unable to find the instance/port 'mipi_data_p_in1[1]' in the constraint 'ldc_set_location -site {C1} [get_ports {mipi_data_p_in1[1]}]'

### ISSUE THREAD

**Issue by INDNextHenry** [circuitvalley/USB_C_Industrial_Camera_FPGA_USB3#16]
Hi @circuitvalley 

Full fpga build log.
[fpga-build-log.txt](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/files/12657952/fpga-build-log.txt)

I still try to repuduected this project, I encountered no signal output from some key pins(like Frame-sync, Line-Sync). 
![image](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/9445e8da-9f5a-42ef-8099-ae4ccd000bab)

I found some clues when checking the compilation information. Does this mean that some signals of mipi are not configured correctly? 
![image](https://github.com/circuitvalley/USB_C_Industrial_Camera_FPGA_USB3/assets/115602758/455345ff-9f88-4e88-b7f0-ff1328531340)

I am using the default pdc file, please give me some suggestions, thank you.

**Comment by circuitvalley** [comment]
Comment from code. If you do not have ES chip then you can remove second MIPI port from top level. 

//Lattice FPGA Engineering sample chip does not allow manual PHY pin assignment* for PHY and our hardware uses PHY1 rather than PHY0, this instance with go to PHY0 while our actual instance will go to PHY 1
//*Lattice Does allow manual pin assignment but when you assign manually PHY will not work at all. Appears to be ES chip bug.
//As i am using Lattice ES chips i need to use Radiant 2.0 , DPHY IP has been changed a little with Radiant 3.1
// If using ES Devices a dummy dphy_ip need to inferred as a place holder
